name: Deploy to DigitalOcean Droplet

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up SSH Agent to connect to your Droplet
      - name: Set up SSH agent
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Install dependencies
        run: npm install

      - name: Run build
        run: npm run build

      # Deploy to the Droplet using Rsync
      - name: Deploy to Droplet via SSH
        run: rsync -avz --delete ./dist root@167.71.188.90:/var/www/nextjs-app/

      # Restart the app on the Droplet
      - name: SSH into Droplet and build project
        run: |
          ssh root@167.71.188.90 << 'EOF'
            cd /var/www/nextjs-app

            echo "Restarting app using pm2..."
            pm2 restart nextjs-app || pm2 start npm --name "nextjs-app" -- start

            echo "Deployment complete!"
          EOF
